{% set version = "1.3.3" %}

package:
  name: simplekml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simplekml/simplekml-{{ version }}.tar.gz
  sha256: 6e0fcb56a6da81fc1326552544d759ceaec9b6b53694851b937e208add238222

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simplekml

about:
  home: http://www.simplekml.com/en/latest/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: A Simple KML creator

extra:
  recipe-maintainers:
    - ocefpaf
