{% set version = "1.3.0" %}

package:
  name: simplekml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simplekml/simplekml-{{ version }}.zip
  sha256: 6c6232de5a6a6020101c7220e9bbd8e68852d9a62d8eac9a472266a941b7b7e6

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simplekml

about:
  home: http://www.simplekml.com/en/latest/
  license: LGPL-3.0
  summary: A Simple KML creator

extra:
  recipe-maintainers:
    - ocefpaf
