{% set version = "1.3.1" %}

package:
  name: simplekml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simplekml/simplekml-{{ version }}.tar.gz
  sha256: 30c121368ce1d73405721730bf766721e580cae6fbb7424884c734c89ec62ad7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simplekml

about:
  home: http://www.simplekml.com/en/latest/
  license: LGPL-3.0
  summary: A Simple KML creator

extra:
  recipe-maintainers:
    - ocefpaf
