travis:
  secure:
    BINSTAR_TOKEN: E1R73Sz5XbP/uCI7Ckjip0a41g6UErjC6VrVLJc3jk9eBbo3Ad+ZDj/TWJXJNPAO5oODdUrzMtfzi7VIe+JbYvI1RNsOwEBpreH4TL9nVrLgYKIhcYlGHQ6yvB/+p5Fu5sPsRVTdsh1/oUalnakKsttkWHzD4rdCkAl2kXPN9PcSvg0V0pdzQvEq1UVCUPrgRZo4kYzX6b+ZlfJeKbrenMAHtGmtJZeASjJcNI6V0KThw7TQR7TVnY+N5be1gGOnFMgWjEH6KioFEEdmrvgOW69heSgZcQmJK6Q1AcwNVwUsxgKByasOcyfaH6RdkwKkiYTENIZpQ72oNtBXFwv+zE2R97ZIyTQu8fM4fl0LjDOveztv6LzMBx9yvgfy97iCyxVer74ZnCBYO6Cs7+lgc5O7pEfLBWGbiCb0R/vv6kzJ8IkbAEbhsH2Y0MUBANk8hZ3X8rUm+kmjXWn8hsRWvdh8yoMGzAKlDjp515zU4oknXSBh8vCr6Mx04s/ZH2Us4fZfRXzvQb/rSdc8IRnKg0OBY2nUmME6ZN2pRr9nbwuskYo7UoQ/acKAnBDcfCX32FuGuI5BnJF01l3coBOzqQ7IHqJmfHwt89qTYoiH3Rczv9FHIKNr6VePq4YEx+o43HayJH5M3O3STWfo1c+8wzoUrP01GimI2QLau9s3kJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
